"""Write requirements.txt pinned to whatever is installed in this environment.

Run once on the pod, from the repo root, inside the env the project actually runs in:

    python scripts/make_requirements.py

The list is the set of third-party packages the repository imports, plus `accelerate`,
which transformers' Trainer needs at runtime without importing it by name, plus jupyterlab to open
the tutorial, plus the spaCy model, which cannot be installed from PyPI and so is pinned by its release URL.

Local version labels are stripped, so a CUDA build recorded as `2.3.1+cu121` is pinned as
`2.3.1`. pip cannot resolve `+cu121` from PyPI, and a CPU user can still install the same
release.
"""
import importlib.metadata as md
import sys
from pathlib import Path

PACKAGES = ["accelerate", "bioc", "datasets", "ipywidgets", "matplotlib", "numpy",
            "openai", "pandas", "pydantic", "requests", "scikit-learn", "spacy",
            "torch", "tqdm", "transformers", "jupyterlab"]

MODEL_URL = ("en_core_web_sm @ https://github.com/explosion/spacy-models/releases/"
             "download/en_core_web_sm-{v}/en_core_web_sm-{v}-py3-none-any.whl")


def main(out="requirements.txt"):
    lines, missing = [], []
    for p in PACKAGES:
        try:
            lines.append(f"{p}=={md.version(p).split('+')[0]}")
        except md.PackageNotFoundError:
            missing.append(p)
    try:
        lines.append(MODEL_URL.format(v=md.version("en_core_web_sm")))
    except md.PackageNotFoundError:
        missing.append("en_core_web_sm")

    header = (f"# generated by scripts/make_requirements.py\n"
              f"# python {sys.version_info.major}.{sys.version_info.minor}\n")
    Path(out).write_text(header + "\n".join(lines) + "\n")
    print(f"wrote {out}, {len(lines)} pins")
    for l in lines:
        print(f"  {l}")
    if missing:
        print(f"\nnot installed here, so not pinned: {', '.join(missing)}")
        print("check this is the env the project runs in before committing")


if __name__ == "__main__":
    main()
